/*
 * PATH /src/errors/error-codes.d.ts
 */

/**
 * Application error codes.
 */
export const ErrorCodes: Readonly<{
  INTERNAL_ERROR: 'INTERNAL_ERROR'

  INVALID_JSON: 'INVALID_JSON'
  INVALID_YAML: 'INVALID_YAML'

  INVALID_CONFIG: 'INVALID_CONFIG'
  CONFIG_NOT_FOUND: 'CONFIG_NOT_FOUND'
  MISSING_REQUIRED_OPTION: 'MISSING_REQUIRED_OPTION'

  PROJECT_NOT_INITIALIZED: 'PROJECT_NOT_INITIALIZED'
  PROJECT_FILE_NOT_FOUND: 'PROJECT_FILE_NOT_FOUND'

  INVALID_NAME: 'INVALID_NAME'
  PATH_OUTSIDE_BASE_DIRECTORY: 'PATH_OUTSIDE_BASE_DIRECTORY'
  TARGET_DIRECTORY_NOT_EMPTY: 'TARGET_DIRECTORY_NOT_EMPTY'

  SERVICE_ALREADY_EXISTS: 'SERVICE_ALREADY_EXISTS'
  MODEL_ALREADY_EXISTS: 'MODEL_ALREADY_EXISTS'
  DOCKER_SERVICE_ALREADY_EXISTS: 'DOCKER_SERVICE_ALREADY_EXISTS'

  PERMISSION_DENIED: 'PERMISSION_DENIED'

  DEPENDENCY_VERSION_CONFLICT: 'DEPENDENCY_VERSION_CONFLICT'
  DEPENDENCY_SCOPE_CONFLICT: 'DEPENDENCY_SCOPE_CONFLICT'
  PACKAGE_LOCK_RESOLUTION_FAILED: 'PACKAGE_LOCK_RESOLUTION_FAILED'
}>

/**
 * Union of all supported application error codes.
 */
export type ErrorCode = typeof ErrorCodes[keyof typeof ErrorCodes]