export const ErrorCodes = Object.freeze({
  INTERNAL_ERROR: 'INTERNAL_ERROR',

  // Parsing error in config
  INVALID_JSON: 'INVALID_JSON',
  INVALID_YAML: 'INVALID_YAML',

  // Missing field in config
  INVALID_CONFIG: 'INVALID_CONFIG',

  CONFIG_NOT_FOUND: 'CONFIG_NOT_FOUND',
  MISSING_REQUIRED_OPTION: 'MISSING_REQUIRED_OPTION',

  PROJECT_NOT_INITIALIZED: 'PROJECT_NOT_INITIALIZED',
  PROJECT_FILE_NOT_FOUND: 'PROJECT_FILE_NOT_FOUND',

  INVALID_NAME: 'INVALID_NAME',
  PATH_OUTSIDE_BASE_DIRECTORY: 'PATH_OUTSIDE_BASE_DIRECTORY',
  TARGET_DIRECTORY_NOT_EMPTY: 'TARGET_DIRECTORY_NOT_EMPTY',

  SERVICE_ALREADY_EXISTS: 'SERVICE_ALREADY_EXISTS',
  MODEL_ALREADY_EXISTS: 'MODEL_ALREADY_EXISTS',
  DOCKER_SERVICE_ALREADY_EXISTS: 'DOCKER_SERVICE_ALREADY_EXISTS',

  PERMISSION_DENIED: 'PERMISSION_DENIED'
})
