import fs from 'node:fs/promises'
import path from 'node:path'
import { expect } from 'vitest'

import { readJsonFile } from '../../src/utils/fs-helpers.js'

const getGeneratedServiceConfig = async (projectDir, serviceName) => {
  const configPath = path.join(projectDir, '.moleculer-gen', 'config.json')
  const config = await readJsonFile(configPath)

  if (Array.isArray(config.services)) {
    return config.services.find(service => service.serviceName === serviceName)
  }

  return config.services?.[serviceName]
}

/**
 * Path expected from the input config.
 *
 * Used before running the command, when the generated
 * service config may not exist yet.
 */
export const getExpectedServiceDirectoryPath = (projectDir, service) => {
  return path.join(
    projectDir,
    'src',
    'services',
    service.serviceDirectoryName ?? service.serviceName
  )
}

/**
 * Paths expected after generation.
 *
 * These are deliberately resolved from the test's expected
 * values, never from the config generated by moleculer-gen.
 *
 * This keeps the test oracle independent from the code
 * under test.
 */
const getExpectedGeneratedServiceDirectoryPath = (projectDir, expectedService) => {
  expect(expectedService.serviceDirectoryName).toBeDefined()

  return path.join(
    projectDir,
    'src',
    'services',
    expectedService.serviceDirectoryName
  )
}

const getExpectedGeneratedServiceFilePath = (projectDir, expectedService) => {
  expect(expectedService.serviceDirectoryName).toBeDefined()
  expect(expectedService.serviceFileName).toBeDefined()

  return path.join(
    projectDir,
    'src',
    'services',
    expectedService.serviceDirectoryName,
    expectedService.serviceFileName
  )
}

/**
 * Assertions on the initial filesystem state.
 *
 * These can still be used with the raw input config because
 * they run before moleculer-gen has generated anything.
 */

export const expectServiceToExist = async (projectDir, service) => {
  const serviceDirectoryPath = getExpectedServiceDirectoryPath(
    projectDir,
    service
  )
  await expect(
    fs.access(serviceDirectoryPath)
  ).resolves.toBeUndefined()
}

export const expectServiceNotToExist = async (projectDir, service) => {
  const serviceDirectoryPath =
    getExpectedServiceDirectoryPath(
      projectDir,
      service
    )

  await expect(
    fs.access(serviceDirectoryPath)
  ).rejects.toThrow()
}

export const expectServicesToExist = async (projectDir, services) => {
  for (const service of services) {
    await expectServiceToExist(
      projectDir,
      service
    )
  }
}

export const expectServicesNotToExist = async (projectDir, services) => {
  for (const service of services) {
    await expectServiceNotToExist(
      projectDir,
      service
    )
  }
}

/**
 * Assertions on generated artifacts.
 *
 * All paths below are derived from explicit expected values
 * supplied by the test, never from generated config.
 */

export const expectGeneratedServiceDirectoryToExist = async (projectDir, expectedService) => {
  const serviceDirectoryPath = getExpectedGeneratedServiceDirectoryPath(
    projectDir,
    expectedService
  )

  await expect(
    fs.access(serviceDirectoryPath)
  ).resolves.toBeUndefined()
}

export const expectServiceFileToExist = async (projectDir, expectedService) => {
  const serviceFilePath = getExpectedGeneratedServiceFilePath(
    projectDir,
    expectedService
  )

  await expect(
    fs.access(serviceFilePath)
  ).resolves.toBeUndefined()
}

export const expectCrudArtifactsToExist = async (projectDir, expectedService) => {
  expect(expectedService.isCrud).toBe(true)

  expect(expectedService.modelFileName).toBeDefined()

  const modelPath = path.join(
    projectDir,
    'src',
    'data',
    'model',
    expectedService.modelFileName
  )

  await expect(
    fs.access(modelPath)
  ).resolves.toBeUndefined()
}

export const expectApiArtifactsToExist = async (projectDir, expectedService) => {
  expect(expectedService.exposeApi).toBe(true)

  expect(expectedService.serviceDirectoryName).toBeDefined()

  const routesConfigPath = path.join(
    projectDir,
    'src',
    'config',
    'routes.config.js'
  )

  const routesConfig = await fs.readFile(routesConfigPath, 'utf8')

  expect(routesConfig).toContain(`/api/v1/${expectedService.serviceDirectoryName}`)

  for (const action of [
    'create',
    'list',
    'get',
    'update',
    'remove'
  ]) {
    expect(routesConfig).toContain(`${expectedService.serviceName}.${action}`)
  }
}

export const expectDockerArtifactToExist = async (projectDir, expectedService) => {
  expect(
    expectedService.serviceDirectoryName
  ).toBeDefined()

  const dockerServicePath = path.join(
    projectDir,
    'docker',
    'services',
    `${expectedService.serviceDirectoryName}.yaml`
  )

  await expect(
    fs.access(dockerServicePath)
  ).resolves.toBeUndefined()
}

/**
 * Assert that moleculer-gen persisted the exact values
 * expected by the test.
 *
 * Derived/default values must be explicitly provided by
 * the test fixture if they are part of the behaviour being
 * tested.
 */
const expectGeneratedServiceConfigToMatchExpected = async (projectDir, expectedService) => {
  const generatedService = await getGeneratedServiceConfig(
    projectDir,
    expectedService.serviceName
  )

  expect(generatedService).toBeDefined()
  expect(generatedService).toMatchObject(expectedService)

  return generatedService
}

export const expectServiceArtifacts = async (projectDir, expectedService) => {
  await expectGeneratedServiceConfigToMatchExpected(projectDir, expectedService)
  await expectGeneratedServiceDirectoryToExist(projectDir, expectedService)
  await expectServiceFileToExist(projectDir, expectedService)
  await expectDockerArtifactToExist(projectDir, expectedService)
  if (expectedService.isCrud) {
    await expectCrudArtifactsToExist(projectDir, expectedService)
  }
  if (expectedService.exposeApi) {
    await expectApiArtifactsToExist(projectDir, expectedService)
  }
}

export const expectGeneratedArtifacts = async (projectDir, expectedServices) => {
  for (const expectedService of expectedServices) {
    await expectServiceArtifacts(projectDir, expectedService)
  }
}
